version: 2.1

orbs:
  heroku: circleci/heroku@1.2.4

workflows:
  heroku_deploy:
    jobs:
      - deploy_to_heroku:
          filters:
            branches:
              only: /customer-.*/
jobs:
  deploy_to_heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Setup ENVs
          command: |
            echo "export HEROKU_APP_NAME=$CIRCLE_BRANCH" >> $BASH_ENV
            source $BASH_ENV
            echo "Branch: $CIRCLE_BRANCH"
            echo "Heroku app: $HEROKU_APP_NAME"
      - heroku/deploy-via-git
  
